# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notify.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnotify.proto\x12\x06notify\"E\n\rNotifyRequest\x12\x1a\n\x04item\x18\x01 \x01(\x0b\x32\x0c.notify.Item\x12\n\n\x02ip\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\t\"|\n\x04Item\x12\x0e\n\x06itemId\x18\x01 \x01(\t\x12\r\n\x05price\x18\x02 \x01(\x02\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x10\n\x08quantity\x18\x06 \x01(\x05\x12\x0e\n\x06rating\x18\x07 \x01(\x02\"!\n\x0eNotifyResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2H\n\rNotifyService\x12\x37\n\x06Notify\x12\x15.notify.NotifyRequest\x1a\x16.notify.NotifyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notify_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_NOTIFYREQUEST']._serialized_start=24
  _globals['_NOTIFYREQUEST']._serialized_end=93
  _globals['_ITEM']._serialized_start=95
  _globals['_ITEM']._serialized_end=219
  _globals['_NOTIFYRESPONSE']._serialized_start=221
  _globals['_NOTIFYRESPONSE']._serialized_end=254
  _globals['_NOTIFYSERVICE']._serialized_start=256
  _globals['_NOTIFYSERVICE']._serialized_end=328
# @@protoc_insertion_point(module_scope)
